### ISSUE TITLE
请问能支持引导到Windows安装包iso上吗?

### ISSUE THREAD

**Issue by imzgg** [zwj4031/ipxefm#1]
你好，我使用代码内的pcbiosisowithmemdisk  pcbiosisowithgrub    efiisowithgrub efiisowithgrubmemrt  efiisowithimgboot 等方法，在vm16上，无论使用bios还是uefi都无法引导进windows官方安装包iso里面，比如cn_windows_7_ultimate_with_sp1_x64_dvd_u_677408.iso，请问有方法可以用ipxe引导进官方windows安装包iso吗

**Comment by zwj4031** [comment]
这个需要Grub2，用另外的项目可以实现，[netgrubfm](https://github.com/zwj4031/netgrubfm)
